### ISSUE TITLE
Valetudo Mapper: Unexpected token  in JSON

### ISSUE THREAD

**Issue by robotastic-io** [rand256/valetudo#230]
**Describe the bug**
Valetudo mapper throws unexpected token error.

**How to Reproduce**
1. Install ValetudoRE 0.9.4
2. Git clone valetudo-mapper or download release 0.2.0 from official repo: https://github.com/rand256/valetudo-mapper
3. npm install
4. run npm start in folder
5. An error message is displayed (see stacktrace below)

**Expected behavior**
Map is posted to topic or available as PNG

**Stacktrace**

` /valetudo-mapper-0.2.0
> node app.js
Loading configuration file: /home/valetudomap/valetudo-mapper-0.2.0/config.json
Connecting to MQTT Broker
Connected to MQTT Broker
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.client.on (/home/valetudomap/valetudo-mapper-0.2.0/lib/MqttClient.js:73:42)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/mqtt/lib/client.js:336:12)
    at work (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/valetudomap/valetudo-mapper-0.2.0/node_modules/readable-stream/lib/_stream_writable.js:334:11)`

**Vacuum Model:** 
Gen2

**Valetudo Version:** 
0.9.4

**Tested Valetudo Mapper Version:**
0.2.0
latest commit

**Additional context**
Vac Firmware 1886
iobroker mqtt broker

**Comment by rand256** [comment]
This trace is from 0.2.0, which is 1+ year old and actually is even a pre-fork release. It definitely won't work with modern valetudo RE.
You need to git clone current master.

**Comment by robotastic-io** [comment]
Hi,

i get the same result as mentioned in step 2. See stacktrace and git log below. Let me know if you need anything else.



 ```
npm start

> valetudo-mapper@0.5.0 start /home/valetudomap/valetudo-mapper
> node app.js

Loading configuration file: /home/valetudomap/valetudo-mapper/config.json
Connecting to MQTT Broker
Connected to MQTT Broker
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.client.on (/home/valetudomap/valetudo-mapper/lib/MqttClient.js:90:46)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/home/valetudomap/valetudo-mapper/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/valetudomap/valetudo-mapper/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/valetudomap/valetudo-mapper/node_modules/readable-stream/lib/_stream_writable.js:334:11)
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.client.on (/home/valetudomap/valetudo-mapper/lib/MqttClient.js:90:46)
    at MqttClient.emit (events.js:198:13)
    at MqttClient._handlePublish (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:1162:12)
    at MqttClient._handlePacket (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:351:12)
    at work (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:283:12)
    at Writable.writable._write (/home/valetudomap/valetudo-mapper/node_modules/mqtt/lib/client.js:294:5)
    at doWrite (/home/valetudomap/valetudo-mapper/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/valetudomap/valetudo-mapper/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/valetudomap/valetudo-mapper/node_modules/readable-stream/lib/_stream_writable.js:334:11)
^C
valetudomap@raspberrypi:~/valetudo-mapper $ git log
commit 8e23ac21e3627e376792de907ccf725e73094408
Author: Erinome <rand256@yandex.ru>
Date:   Fri Apr 24 19:08:14 2020 +0300

    update README.md

```

**Comment by rand256** [comment]
Valetudo RE sends map data in binary format, so I guess the issue is that your mqtt broker does something wrong when processing it. There is [some](https://github.com/ioBroker/ioBroker.mqtt/issues/48) [evidence](https://github.com/ioBroker/ioBroker.mqtt/issues/64) of that. I'd suggest you to try running i.e. mosquitto to check whether your issue is actually caused by the broker.

**Comment by robotastic-io** [comment]
I just checked with mosquitto as per your suggestion and it is working fine. It seems the issue is indeed with the iobroker mqtt broker, the used mqtt library or iobroker data handling. I will keep inquiring in that direction. Thanks for talking the time to point me in the right direction.
