### ISSUE TITLE
Error on start testing git

### ISSUE THREAD

**Issue by thejoe8495** [rand256/valetudo#31]
At start the current git repository testing this error apear:  

failed to get handshake for message: get_timezone [] { retries: 92, retriesHS: 102 }
/home/joe/git/valetudo/lib/miio/Vacuum.js:91
        throw new Error("Unable to reach vacuum, handshake failed");
        ^

Error: Unable to reach vacuum, handshake failed
    at Vacuum.sendMessage (/home/joe/git/valetudo/lib/miio/Vacuum.js:91:15)
    at Vacuum.<anonymous> (/home/joe/git/valetudo/lib/miio/Vacuum.js:145:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**How to Reproduce**
Firmware 1886
npm install
npm run build
sudo ./develop/run
wait 10 seconds

**Expected behavior**

running ;)

**Vacuum Model:** 
Gen2/S5

**Valetudo Version:** 
git repository

**User-Agent**  
not needet  

**Additional context**
running on ubuntu 19.04 latest patches

**Comment by thejoe8495** [comment]
My config from hypfer was not copied :unamused:
For all with the same error, the VAC_TOKEN was wrong
