### ISSUE TITLE
No request was made - pre-rooted RE pkg

### ISSUE THREAD

**Issue by Setsua** [rand256/valetudo#367]
I received my 2nd Xiaomi Mi Robot Vacuum V1 and wanted to root it to install valetudo RE like my 1st one.. So I downloaded the pre-rooted images and installed all prerequisites on my ubuntu notebook. Then connected to the open wifi hotspot the vacuum provided but when i tried to install the update i got an error. Unfortunately I did not find a solution online but a comment that my device is possibly a newer revision which makes it impossible to root it locally (dunno if its true)
I also made a factory reset which might had led to an older version of the os but it didn't work.

`
(venv) whatever@device:~/robocop$ mirobo --debug --ip 192.168.8.1 --token 12345XXXXXXXXXXXXXXXXX update-firmware /home/whatever/Downloads/Vaccuum/root_4018.pkg
INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Read stored sequence ids: {'seq': 1317, 'manual_seq': 0}
DEBUG:miio.vacuum_cli:Connecting to 192.168.8.1 with token 12345XXXXXXXXXXXXXXXXX
Going to update from /home/whatever/Downloads/Vaccuum/root_4018.pkg
INFO:miio.updater:Serving on 0.0.0.0:41597, timeout 10
INFO:miio.updater:Using local /home/whatever/Downloads/Vaccuum/root_4018.pkg (md5: 244998f603e95f314bc8f8d66fa2f8f0)
DEBUG:miio.updater:available interfaces: ['eno1', 'wlp3s0']
DEBUG:miio.updater:eno1 has no ipv4 addresses, skipping
DEBUG:miio.updater:Got addr: 192.168.8.219
Hosting file at http://192.168.8.219:41597/root_4018.pkg
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x17V\xfc\xa8\x00\x00\x02\x9a' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('1756fca8')
            ts = 1970-01-01 00:11:06
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'8pIu56SsRIqPkez0' (total 16)
DEBUG:miio.miioprotocol:Discovered 1756fca8 with ts: 1970-01-01 00:11:06, token: b'12345XXXXXXXXXXXXXXXXX'
DEBUG:miio.miioprotocol:192.168.8.1:54321 >>: {'id': 1318, 'method': 'miIO.ota', 'params': {'mode': 'normal', 'install': '1', 'app_url': 'http://192.168.8.219:41597/root_4018.pkg', 'file_md5': '244998f603e95f314bc8f8d66fa2f8f0', 'proc': 'dnld install'}}
DEBUG:miio.protocol:Unable to parse json '': Expecting value: line 1 column 1 (char 0)
DEBUG:miio.click_common:Exception: Unable to parse message payload
Traceback (most recent call last):
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/protocol.py", line 193, in _decode
    return json.loads(decoded)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/vacuum_cli.py", line 617, in update_firmware
    update_res = vac.update(url, md5)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/device.py", line 197, in update
    return self.send("miIO.ota", payload)[0] == "ok"
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/device.py", line 143, in send
    return self._protocol.send(
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/miioprotocol.py", line 193, in send
    m = Message.parse(data, token=self.token)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 1981, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 2439, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 3987, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 4265, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/construct/core.py", line 698, in _parse
    return self._decode(obj, context, path)
  File "/home/whatever/robocop/flasher/venv/lib/python3.8/site-packages/miio/protocol.py", line 199, in _decode
    raise PayloadDecodeException(
miio.exceptions.PayloadDecodeException: Unable to parse message payload
Error: Unable to parse message payload
ERROR:miio.updater:No request was made..
`

Hope someone can assist me here.

**Comment by pidator** [comment]
This isn't a Valetudo RE issue, more a general robot rooting issue and isn't related to the prebuild pkg. The [Q&A Section](https://github.com/rand256/valetudo/discussions/categories/q-a) would be an appropriate place for asking this.
