### ISSUE TITLE
Can no longer flash firmware

### ISSUE THREAD

**Issue by stevenroose** [rand256/valetudo#38]
So I tried to install this version of valetudo and since the maps were not working (see issue), I wanted to reinstall stock valetudo.

So somehow my usual procedure to flash the firmware using mirobo in some awkward venv construction (I can't find the document that actually instructed me this unfortunately, but it has always worked in the past). So somehow during this install, it failed with the following message:

```
$ mirobo --ip 192.168.8.1 --token 785a79774c434b4b4f594b476a533757 update-firmware ../output/vacuum_1910.pkg
Going to update from ../output/vacuum_1910.pkg
INFO:miio.updater:Serving on 0.0.0.0:38143, timeout 10
INFO:miio.updater:Using local ../output/vacuum_1910.pkg (md5: 0973be74c20c0316d244f033b3d97d6c)
Hosting file at http://192.168.8.39:38143/vacuum_1910.pkg
ERROR:miio.protocol:unable to parse json '': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/device.py", line 257, in send
    data, addr = s.recvfrom(1024)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steven/software/rockrobo/flasher/venv/bin/mirobo", line 10, in <module>
    sys.exit(cli())
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/vacuum_cli.py", line 590, in update_firmware
    update_res = vac.update(url, md5)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/device.py", line 328, in update
    return self.send("miIO.ota", payload)[0] == "ok"
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/device.py", line 286, in send
    return self.send(command, parameters, retry_count - 1)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/device.py", line 263, in send
    self.__id = m.data.value["id"]
TypeError: 'NoneType' object is not subscriptable
ERROR:miio.updater:No request was made..
```

I'm pretty sure this is not directly related to this repo's software, but I would very much appreciate a word of advice as to how to actually flash any new firmware into this device without mirobo working :/
I tried resetting the device with the reset button and flashing again afterwards, also using the ususal procedure. (I have the IP correct, I have the token correct (`mirobo --debug discover --handshake true`).)

**Comment by rand256** [comment]
Latest firmware versions like 1910 or 4004 have their miio components upgraded, and now they simply disallow local firmware installation. Do a factory reset to return back to previous firmware versions.
