### ISSUE TITLE
Issue building most recent release

### ISSUE THREAD

**Issue by jbrink90** [rand256/valetudo#461]
**Describe the bug**
Building 0.10.0 from 'npm run build' returns:

```
> valetudo-re@0.10.0 prebuild /home/billy/Desktop/projects/valetudo
> cp -a client client.b && find client/ -type f \( -iname \*.json -o -iname \*.js -o -iname \*.html -o -iname \*.css \) -ex                                                                   ec gzip -9 {} +


> valetudo-re@0.10.0 build /home/billy/Desktop/projects/valetudo
> pkg --targets node12.22.1-linux-armv7 --no-bytecode --options max-old-space-size=32,optimize_for_size --public-packages=p                                                                   rettycron . --output valetudo

sh: 1: pkg: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! valetudo-re@0.10.0 build: `pkg --targets node12.22.1-linux-armv7 --no-bytecode --options max-old-space-size=32,opt                                                                   imize_for_size --public-packages=prettycron . --output valetudo`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the valetudo-re@0.10.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/billy/.npm/_logs/2021-08-29T00_09_01_576Z-debug.log
```

**How to Reproduce**
npm run build

**Expected behavior**

Successful build.

**Screenshots**
```
15 silly lifecycle valetudo-re@0.10.0~build: Args: [
15 silly lifecycle   '-c',
15 silly lifecycle   'pkg --targets node12.22.1-linux-armv7 --no-bytecode --options max-old-space-size=32,optimize_for_size --public-packages=prettycron . --output valetudo'
15 silly lifecycle ]
16 silly lifecycle valetudo-re@0.10.0~build: Returned: code: 126  signal: null
17 info lifecycle valetudo-re@0.10.0~build: Failed to exec build script
18 verbose stack Error: valetudo-re@0.10.0 build: `pkg --targets node12.22.1-linux-armv7 --no-bytecode --options max-old-space-size=32,optimize_for_size --public-packages=prettycron . --out$
18 verbose stack Exit status 126
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18 verbose stack     at EventEmitter.emit (events.js:200:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:200:13)
18 verbose stack     at maybeClose (internal/child_process.js:1021:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
19 verbose pkgid valetudo-re@0.10.0
20 verbose cwd /home/billy/Desktop/projects/valetudo
21 verbose Linux 4.15.0-58-generic
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
23 verbose node v12.5.0
24 verbose npm  v6.9.2
25 error code ELIFECYCLE
26 error errno 126
27 error valetudo-re@0.10.0 build: `pkg --targets node12.22.1-linux-armv7 --no-bytecode --options max-old-space-size=32,optimize_for_size --public-packages=prettycron . --output valetudo`
27 error Exit status 126
28 error Failed at the valetudo-re@0.10.0 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 126, true ]
```

**Vacuum Model:** 

**Valetudo Version:** 
0.10.0

**User-Agent** 

**Additional context**

**Comment by jbrink90** [comment]
I was able to resolve this issue by deleting node_modules and re-installing them.
